export const DEFAULT_ABBREVIATION_ALLOW_LIST = ['fn', 'cb', 'err', 'prev', 'dev', 'i'];

export const ABBREVIATION_REPLACEMENTS: Record<string, Record<string, boolean> | false> = {
  ref: false,
  refs: false,
  dev: false,
  dir: false,
  env: false,
  prop: false,
  props: false,
  util: false,
  utils: false,
  param: false,
  params: false,
  arg: false,
  args: false,
  ev: { event: true },
  val: { value: true },
  msg: { message: true },
  el: { element: true },
  elem: { element: true },
  btn: { button: true },
  cb: { callback: true },
  fn: { function: true },
  err: { error: true },
  opts: { options: true },
  cfg: { config: true },
  obj: { object: true },
  arr: { array: true },
  str: { string: true },
  num: { number: true },
  curr: { current: true },
  len: { length: true },
  e: { event: true, error: true },
};
